Applied an additional condition if -XX:-CRIUSecProvider is specified
ibmruntimes/openj9-openjdk-jdk17 pull request #296
Opened 2023-12-08 16:29 UTC by WilburZjh

Back-ported from https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/689

2023-12-08 16:29 UTC, WilburZjh commented
@jasonkatonica FYI

2023-12-08 17:58 UTC, keithc-ca requested changes
Please update the commit message; it should be "written in the imperative mood".
See https://github.com/eclipse-openj9/openj9/blob/master/CONTRIBUTING.md#commit-guidelines.

2023-12-08 17:58 UTC, keithc-ca commented on src/java.base/share/classes/java/security/Security.java
> +            }
This should be the same as in later streams (also `isEnableFullSecurityEnvInCRIU` doesn't exist).

2023-12-08 18:47 UTC, keithc-ca commented
I see you changed the title of this PR: The commits should be squashed and the commit message should be similar.

2023-12-08 18:48 UTC, WilburZjh commented
> I see you changed the title of this PR: The commits should be squashed and the commit message should be similar.

Yes, once the build is finished, i will update them all.

2023-12-08 19:45 UTC, WilburZjh commented
Build pass: https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/19781/

Commits are squashed

2023-12-08 20:05 UTC, keithc-ca commented
Jenkins test sanity plinux jdk17

2023-12-09 00:36 UTC, keithc-ca approved these changes

2023-12-09 00:36 UTC, merged