Use Unsafe.compareAndSwap for writing to Stable field and array
ibmruntimes/openj9-openjdk-jdk17 pull request #325
Opened 2024-02-23 21:06 UTC by nbhuiyan

Using Unsafe.compareAndSwap prevents issues resulting from multiple threads coming across uninitialized VarHandle.typesAndInvokers field and competing to populate the field with their own versions. Using compareAndSwap to populate the typesAndInvokers' MethodHandle table also prevents similar issues when multiple threads come across the same unpopulated slot in the table and compete to populate it.

Issue: eclipse-openj9/openj9#18882

2024-02-23 21:10 UTC, pshipton commented on src/java.base/share/classes/java/lang/invoke/VarHandle.java
> + * Copyright (c) 2014, 2024, Oracle and/or its affiliates. All rights reserved.
Unless this is backport of OpenJDK changes the Oracle copyright shouldn't change. Pls add an IBM copyright statement.

2024-02-23 21:11 UTC, pshipton commented
The change order should be head, 22, 21, 17.

2024-02-26 16:34 UTC, keithc-ca commented
> The change order should be head, 22, 21, 17.

The head stream should be addressed first (jdknext aka jdk23).

2024-02-26 17:06 UTC, jdmpapin commented
I've opened the jdknext PR here: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/747

2024-02-28 17:17 UTC, jdmpapin commented
Yes, I'll have those open momentarily. The changes in those versions are the same as for jdknext

2024-02-28 17:28 UTC, jdmpapin commented
I've optimistically opened both:
- https://github.com/ibmruntimes/openj9-openjdk-jdk22/pull/28
- https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/132

2024-02-28 19:30 UTC, keithc-ca requested changes

2024-02-28 19:30 UTC, keithc-ca commented on src/java.base/share/classes/java/lang/invoke/VarHandle.java
> +
Please move this just before the static block that initializes it (like newer versions).

2024-02-28 19:47 UTC, keithc-ca approved these changes

2024-02-28 19:48 UTC, keithc-ca commented
Validated locally (similar change included in newer versions).

2024-02-28 19:48 UTC, merged

2024-02-28 19:49 UTC, keithc-ca commented
I think a similar change is needed for https://github.com/ibmruntimes/openj9-openjdk-jdk11; could you put that together, please?

2024-02-28 20:53 UTC, nbhuiyan commented
The problem that these PRs aimed to solve does not apply in JDK11 for two reasons:
* This requires using OpenJDK MethodHandle/VarHandle implementation, which is not the case in OpenJ9 with JDK11 by default.
* Even if OpenJDK MH/VH were enabled in JDK11, the VarHandle-related optimizations necessary for the race condition to be a problem is only enabled for JDK17+.

2024-02-28 21:15 UTC, keithc-ca commented
It is my understanding that we intend to adopt OpenJDK MethodHandle/VarHandle implementation in jdk11 at some point. I think it better to address the known problem now rather than hope we'll remember or notice that a change is needed (because a test fails, or, worse, a customer has a problem).