Java CLASSPATH is searched in reverse order
ibmruntimes/openj9-openjdk-jdk17 pull request #358
Opened 2024-06-11 12:04 UTC by srutjay

Backport of 8308184: Launching java with large number of jars in classpath with java.protocol.handler.pkgs system property set can lead to StackOverflowError

2024-06-11 12:05 UTC, srutjay commented
@keithc-ca/ @joransiu  Can you please review this PR

2024-06-11 12:55 UTC, keithc-ca requested changes
Please also fix the commit message so it follows the guidelines at https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md#commit-guidelines.

2024-06-11 12:55 UTC, keithc-ca commented on src/java.base/share/classes/jdk/internal/loader/URLClassPath.java
> +	// the application class loader uses the built-in protocol handler to avoid protocol
Please indent only with spaces.

2024-06-11 12:55 UTC, keithc-ca commented on test/jdk/jdk/internal/loader/URLClassPath/LargeClasspathWithPkgPrefix.java
> + */
This file should be identical to the version in [jdk21](https://github.com/ibmruntimes/openj9-openjdk-jdk21/blob/openj9/test/jdk/jdk/internal/loader/URLClassPath/LargeClasspathWithPkgPrefix.java) (without the IBM copyright addition).

2024-06-12 17:23 UTC, keithc-ca commented on test/jdk/jdk/internal/loader/URLClassPath/LargeClasspathWithPkgPrefix.java
> + */
These are the remaining unwanted differences in this file.
```sh
$ diff jdk{21,17}/test/jdk/jdk/internal/loader/URLClassPath/LargeClasspathWithPkgPrefix.java
27a28
> import jdk.test.lib.JDKToolFinder;
35a37,38
>  * @summary Verify that an application can be launched when the classpath contains large number of
>  *          jars and the java.protocol.handler.pkgs system property is set
40,41d42
<  * @summary Verify that an application can be launched when the classpath contains large number of
<  *          jars and the java.protocol.handler.pkgs system property is set
128c129,130
<         ProcessBuilder pb = ProcessTools.createTestJavaProcessBuilder(
---
>         String java = JDKToolFinder.getJDKTool("java");
>         ProcessBuilder pb = new ProcessBuilder(java,
138c140
< }
---
> }
\ No newline at end of file
```

2024-06-12 17:27 UTC, keithc-ca commented
> Please also fix the commit message so it follows the guidelines at https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md#commit-guidelines.

The commit message should not be a single line, over 200 characters long. The first line should be a summary of no more than 70 characters, followed by a blank line, then any extra information in lines no more than 72 characters each.

2024-06-25 09:31 UTC, srutjay commented
Closing this PR as the https://github.com/openjdk/jdk17u-dev/pull/2550 PR is already merged.

2024-06-25 09:33 UTC, closed without merging