Allow extension of RestrictedSecurity profiles
ibmruntimes/openj9-openjdk-jdk17 pull request #359
Opened 2024-06-20 17:43 UTC by KostasTsiounis

`RestrictedSecurity` profiles sometimes share a lot of duplicate settings with only minor differences. With these changes the extension, similar to object-orientation, of profiles becomes possible.

More specifically, a profile `A` can extend another a profile `B`, using `RestrictedSecurity.<profile A name>.extends = RestrictedSecurity.<profile B name>`. This allows profile `A` to inherit all of profile `B`'s properties. One can add additional properties to profile `A`, or amend some of the existing ones. That includes overriding, appending or removing from a property (wherever that's applicable).

An additional property is introduced. The `RestrictedSecurity.<profile name>.desc.hash = <hash algorithm>:<hash>` is used to ensure the profile hasn't been unintentionally altered. The profile's properties are hashed using the selected `<hash algorithm>`, and the result is compared to the `<hash>` provided through the property. This property is mandatory for base profiles (i.e., profiles that are not extending anything), and optional for the rest.

Back-ported from: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/793

Signed-off by: Kostas Tsiounis [kostas.tsiounis@ibm.com](mailto:kostas.tsiounis@ibm.com)

2024-06-20 17:49 UTC, KostasTsiounis commented
FYI @keithc-ca

2024-06-20 19:59 UTC, keithc-ca requested changes

2024-06-20 19:59 UTC, keithc-ca commented on closed/src/java.base/share/classes/openj9/internal/security/RestrictedSecurity.java
> +                if (debug != null) {
I see no reason why this file shouldn't be identical to later versions. Please add the debug code before line 772, the blank line before line 868 and update the comment on line 890.

2024-06-21 14:59 UTC, keithc-ca commented
Jenkins test sanity zlinux jdk17

2024-06-24 16:41 UTC, keithc-ca commented
Jenkins test sanity plinux jdk17

2024-06-24 21:12 UTC, keithc-ca commented
POWER Linux build systems are still unavailable.

2024-06-24 21:13 UTC, keithc-ca commented
Jenkins test sanity amac jdk17

2024-06-24 23:47 UTC, keithc-ca approved these changes

2024-06-24 23:47 UTC, merged