Fix crash in native crypto on concurrent Cipher object use with GCM
ibmruntimes/openj9-openjdk-jdk17 pull request #51
Opened 2021-12-08 13:43 UTC by ZainabF92

This is an adaptation of PR openj9-openjdk-jdk16#66. 
I added synchronization to any usage of the following variables in the NativeGaloisCounterMode class: `tagLenBytes`, `ibuffer`, `key`, `iv`, and `aadBuffer`.

Signed-off-by: Zainab Fatmi <zainab@ibm.com>

2021-12-08 16:32 UTC, keithc-ca requested changes

2021-12-08 16:32 UTC, keithc-ca commented on closed/src/java.base/share/classes/com/sun/crypto/provider/NativeGaloisCounterMode.java
> +        synchronized(this) {
Formatting: space after `synchronized` (throughout).

2021-12-08 18:54 UTC, ZainabF92 commented on closed/src/java.base/share/classes/com/sun/crypto/provider/NativeGaloisCounterMode.java
> +    private static synchronized byte[] createIv(SecureRandom rand) {
My mistake, that method should not be synchronized.

2021-12-08 18:55 UTC, ZainabF92 commented on closed/src/java.base/share/classes/com/sun/crypto/provider/NativeGaloisCounterMode.java
> +        synchronized(this) {
Done.

2021-12-08 19:08 UTC, keithc-ca commented
Jenkins test sanity.functional,extended.functional,extended.system win,zlinux jdk17

2021-12-09 00:31 UTC, keithc-ca approved these changes

2021-12-09 00:32 UTC, merged

2021-12-09 19:50 UTC, pshipton commented
Is there a change coming soon for jdk11 as well?

2021-12-09 20:43 UTC, ZainabF92 commented
Yes, I will work on that tomorrow

2021-12-09 20:45 UTC, keithc-ca commented
We would also like this fixed in jdk8; see https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/529.