Set native stack size using -Xmso instead of -Xss
ibmruntimes/openj9-openjdk-jdk17 pull request #57
Opened 2022-01-14 17:05 UTC by mikezhang1234567890

OpenJ9 uses -Xmso to set native stack size, so launcher should also use this
value when creating the JVM thread.

Signed-off-by: Mike Zhang <mike.h.zhang@ibm.com>

2022-01-14 17:31 UTC, keithc-ca requested changes

2022-01-14 17:31 UTC, keithc-ca commented on src/java.base/share/native/libjli/java.c
> + */
Please move this to immediately after the Oracle copyright notice.

2022-01-14 17:31 UTC, keithc-ca commented on src/java.base/share/native/libjli/java.c
> +            if ((threadStackSize > 0) && (threadStackSize < (jlong)STACK_SIZE_MINIMUM)) {
Normally we would add parentheses as you've done, but we'd prefer to keep changes relative to upstream as small as reasonably possible. Please revert the change to this line.

2022-01-14 18:06 UTC, keithc-ca commented on src/java.base/share/native/libjli/java.c
> +     * set Java thread size only, which is handled in the JVM code
nit: Please finish sentences with a period.

2022-01-14 20:17 UTC, keithc-ca approved these changes

2022-01-14 22:42 UTC, tajila approved these changes

2022-01-14 22:43 UTC, tajila commented
Jenkins test sanity win jdk8

2022-01-17 14:38 UTC, merged

2022-01-17 14:38 UTC, tajila commented
@mikezhang1234567890 can you make the equivalent change for jdknext,jdk8 & jdk11

2022-01-17 15:08 UTC, keithc-ca commented
Don't forget jdk18.